M2Link/M2Link/Entities/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace M2Link.Entities
{
    public class Message
    {
        [KeyAttribute]
        public Guid Id { get; set; }
        public virtual User Author { get; set; }
        public string Content { get; set; }
        public DateTime Date { get; set; }
        public string Image { get; set; }

        public Message()
        {
            Id = Guid.NewGuid();
        }
    }
}

M2Link/M2Link/Controllers/LoginController.cs
using M2Link.Entities;
using M2Link.Models;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace M2Link.Controllers
{
    public class LoginController : Controller
    {
        // GET : Login/Form
        public ActionResult Form()
        {
            // If the user is already authenticated, redirection on Home page
            if (User.Identity.IsAuthenticated)
            {
                return Redirect("/");
            }

            return View(new LoginModel());
        }

        // POST : Login/Form
        [HttpPost]
        public ActionResult Form(LoginModel model)
        {
            // If the model is not valid, redirect on the same page with model errors
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            User user = UserRepository.Instance.FindByUsername(model.Username);

            // If no user with specified credentials were found
            if (user == null)
            {
                ModelState.AddModelError("Username", "L'utilisateur n'existe pas");
                return View(model);
            }

            // If the hashed password does not match with the hash of the specified password
            if (user.Password != Crypto.SHA256(model.Password))
            {
                ModelState.AddModelError("Password", "Le mot de passe est incorrect");
                return View(model);
            }

            // If credentials are correct, setting up a authentication cookie
            FormsAuthentication.SetAuthCookie(user.Id.ToString(), true);
            
            // Redirect on the Home page
            return Redirect("/");
        }

        // GET: Login/Logout
        public void Logout()
        {
            // Logout from the application and redirect to the login page
            FormsAuthentication.SignOut();
            FormsAuthentication.RedirectToLoginPage();
        }
    }
}

M2Link/M2Link/Controllers/UserController.cs
using M2Link.Entities;
using M2Link.Helpers;
using M2Link.Models;
using M2Link.Shared.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace M2Link.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        // GET : profile
        [Route("profile")]
        public ActionResult MyProfile()
        {
            // Filling the Profile form with the authenticated user information
            return RedirectToAction("GetProfile", new { u = GetAuthenticatedUser().Username });
        }

        // GET : profile/{username}
        [Route("profile/{u}", Name = "GetProfile")]
        public ActionResult GetProfile(string u)
        {
            User user = UserRepository.Instance.FindByUsername(u);

            // If the user does not exist
            if (user == null)
            {
                return View("NotFound");
            }

            return View("~/Views/Profile/Index.cshtml", EntityConverter.createUserModel(user));
        }

        // GET : profile/{username}
        [Route("profile/{u}/followings", Name = "GetProfileFollowings")]
        public ActionResult GetProfileFollowings(string u)
        {
            User user = UserRepository.Instance.FindByUsername(u);

            // If the user does not exist
            if (user == null)
            {
                return View("NotFound");
            }

            ViewBag.AuthenticatedUser = EntityConverter.createUserModel(GetAuthenticatedUser());

            return View("~/Views/Profile/Followings.cshtml", EntityConverter.createUserModel(user));
        }

        // GET : profile/{username}
        [Route("profile/{u}/followers", Name = "GetProfileFollowers")]
        public ActionResult GetProfileFollowers(string u)
        {
            User user = UserRepository.Instance.FindByUsername(u);

            // If the user does not exist
            if (user == null)
            {
                return View("NotFound");
            }

            ViewBag.AuthenticatedUser = EntityConverter.createUserModel(GetAuthenticatedUser());

            return View("~/Views/Profile/Followers.cshtml", EntityConverter.createUserModel(user));
        }

        // GET : profile/{username}/edit
        [Route("profile/{u}/edit", Name = "EditProfile")]
        public ActionResult EditProfile(string u)
        {
            User authenticatedUser = GetAuthenticatedUser();

            // If the authenticated user try to edit the profile of someone else, redirect
            if (authenticatedUser.Username.ToLower() != u.ToLower())
            {
                return RedirectToAction("GetProfile", new { u });
            }

            // Filling the edit profile form with the user information
            EditProfileModel model = new EditProfileModel()
            {
                FirstName = authenticatedUser.FirstName,
                LastName = authenticatedUser.LastName,
                Username = authenticatedUser.Username,
                Mail = authenticatedUser.Mail,
                Description = authenticatedUser.Description
            };

            return View("~/Views/Profile/Edit.cshtml", model);
        }

        // POST : profile/avatar
        [HttpPost]
        [Route("profile/avatar", Name = "EditAvatar")]
        public ActionResult EditAvatar()
        {
            User authenticatedUser = GetAuthenticatedUser();

            var file = Request.Files[0];

            if (file == null || file.ContentLength == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif", ".svg", ".bmp" };
            
                // If the user try to upload a file which is not a image
                if (!allowedExtensions.Contains(Path.GetExtension(file.FileName))) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                string fileName = authenticatedUser.Id.ToString() + Path.GetExtension(file.FileName);
                string filePath = Path.Combine(Server.MapPath("~/Content/Images/Users"), fileName);

                // If the user has already an avatar, delete the old image
                if (authenticatedUser.Avatar != "no_profile_image.png")
                {
                    System.IO.File.Delete(Path.Combine(Server.MapPath("~/Content/Images/Users"), authenticatedUser.Avatar));
                }

                // Save the image
                file.SaveAs(filePath);

                // Update the image reference
                authenticatedUser.Avatar = fileName;

                // Update the database
                UserRepository.Instance.Update(authenticatedUser);

                // Send the image path for the refresh
                return Json(new { success = true, image = fileName }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }


        // POST : profile/edit
        [HttpPost]
        [Route("profile/edit")]
        public ActionResult EditProfile(EditProfileModel model)
        {
            User authenticatedUser = GetAuthenticatedUser();

            // If the user tried to change is username
            if (authenticatedUser.Username != model.Username && UserRepository.Instance.FindByUsername(model.Username) != null )
            {
                ModelState.AddModelError("Username", UserRepository.USERNAME_ALREADY_EXIST_MESSAGE);
            }

            // If the user tried to change is email
            if (authenticatedUser.Mail != model.Mail && UserRepository.Instance.FindByMail(model.Mail) != null)
            {
                ModelState.AddModelError("Mail", UserRepository.MAIL_ALREADY_EXIST_MESSAGE);
            }

            // If the model is not valid, redirect on the same page with model errors
            if (!ModelState.IsValid)
            {
                return View("~/Views/Profile/Edit.cshtml", model);
            }

            // If the user try to changed his password
            if (!string.IsNullOrEmpty(model.Password))
            {
                // If the old password is incorrect
                if (string.IsNullOrEmpty(model.OldPassword) || authenticatedUser.Password != Crypto.SHA256(model.OldPassword))
                {
                    ModelState.AddModelError("OldPassword", "Le mot de passe est incorrect");
                    return View("~/Views/Profile/Edit.cshtml", model);
                }

                // Set the new password
                authenticatedUser.Password = Crypto.SHA256(model.Password);
            }

            // Setting up the new information of the user profile
            authenticatedUser.FirstName = model.FirstName.Trim();
            authenticatedUser.LastName = model.LastName.Trim();
            authenticatedUser.Username = model.Username.Trim();
            authenticatedUser.Mail = model.Mail.Trim();
            authenticatedUser.Description = model.Description.Trim();

            UserRepository.Instance.Update(authenticatedUser);
            
            // Redirect on the Profile page
            return RedirectToAction("MyProfile");
        }

        // GET : users
        [Route("users")]
        public ActionResult GetUsers(string search)
        {
            List<UserModel> users = new List<UserModel>();

            if (string.IsNullOrEmpty(search))
            {
                users = UserRepository.Instance.GetAll().Select(u => EntityConverter.createUserModel(u)).ToList();
            }
            else
            {
                users = UserRepository.Instance.FindByGlobalSearch(search).Select(u => EntityConverter.createUserModel(u)).ToList();
            }

            return View("~/Views/Users/Index.cshtml", users);
        }

        // POST : User/Follow
        [HttpPost]
        public ActionResult Follow(string username)
        {
            try
            {
                User authenticatedUser = GetAuthenticatedUser();
                User targetUser = UserRepository.Instance.FindByUsername(username);

                // If the user try to follow himself
                if (authenticatedUser.Id.Equals(targetUser.Id))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                // Prevent duplicates
                if (!authenticatedUser.Followings.Contains(targetUser))
                {
                    // Update the relation between the two users
                    authenticatedUser.Followings.Add(targetUser);

                    // Update the database
                    UserRepository.Instance.Update(authenticatedUser);
                }

                // Prevent duplicates
                if (!targetUser.Followers.Contains(authenticatedUser))
                {
                    // Update the relation between the two users
                    targetUser.Followers.Add(authenticatedUser);

                    // Update the database
                    UserRepository.Instance.Update(targetUser);
                }

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // POST : User/Unfollow
        [HttpPost]
        public ActionResult Unfollow(string username)
        {
            try
            {
                User authenticatedUser = GetAuthenticatedUser();
                User targetUser = UserRepository.Instance.FindByUsername(username);

                // If the user try to unfollow himself

M2Link/M2Link/Views/Shared/ConnectedLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
</head>

<body>
    <div class="d-flex h-100 mx-auto flex-column">
        <header class="mb-3 text-light">
            <div class="inner mx-auto w-75">
                <nav class="navbar navbar-expand-md navbar-dark row justify-content-between py-2">
                    <div class="col-12 col-md-6">
                        <div class="row justify-content-between">
                            <div class="col-2 my-auto">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                            </div>

                            <div class="col-8 d-block d-md-none my-auto">
                                @{Html.BeginForm("GetUsers", "User", FormMethod.Get);}
                                <div class="input-group">
                                    <input type="text" name="search" class="nav-item form-control" placeholder="Votre recherche">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary py-0" type="submit">
                                            <i class="material-icons" style="line-height: 1.5">search</i>
                                        </button>
                                    </div>
                                </div>
                                @{Html.EndForm();}
                            </div>
                        </div>
                        
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                            <div class="navbar-nav row no-gutters text-center w-100">
                                <a class="nav-item nav-link text-light col" href="@Url.Action("Index", "Home")">
                                    <i class="material-icons align-middle" style="font-size:23px">home</i>
                                    <span class="align-middle">Accueil</span>
                                </a>
                                <a class="nav-item nav-link text-light col" href="@Url.Action("GetUsers", "User")">
                                    <i class="material-icons align-middle" style="font-size:23px">people</i>
                                    <span class="align-middle">Utilisateurs</span>
                                </a>
                                <a class="nav-item nav-link text-light col d-block d-md-none" href="@Url.Action("MyProfile", "User")">
                                    <i class="material-icons align-middle" style="font-size:23px">person</i>
                                    <span class="align-middle">Mon profil</span>
                                </a>
                                <a class="nav-item nav-link text-light col d-block d-md-none" href="@Url.Action("Logout", "Login")">
                                    <i class="material-icons align-middle" style="font-size:23px">exit_to_app</i>
                                    <span class="align-middle">Se déconnecter</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 d-none d-md-block p-0">
                        <div class="row justify-content-end">
                            <div class="col-md-9">
                                @{Html.BeginForm("GetUsers", "User", FormMethod.Get);}
                                <div class="input-group">
                                    <input type="text" name="search" class="nav-item form-control" placeholder="Votre recherche">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary py-0" type="submit">
                                            <i class="material-icons" style="line-height: 1.5">search</i>
                                        </button>
                                    </div>
                                </div>
                                @{Html.EndForm();}
                            </div>
                            
                            <div class="col-2">
                                <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img src="~/Content/Images/Users/no_profile_image.png" width="40" height="40" class="ml-auto avatar my-profile"/>
                                </a>
                                <div class="dropdown-menu text-center text-dark">
                                    @Html.ActionLink("Mon profil", "MyProfile", "User", null, new { @class = "dropdown-item text-dark" })
                                    <div class="dropdown-divider"></div>
                                    @Html.ActionLink("Se déconnecter", "Logout", "Login", null, new { @class = "dropdown-item text-dark" })

                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </header>

        <main role="main" class="w-75 mx-auto">
            @RenderBody()
        </main>

        <footer class="mt-auto mx-auto text-center w-75">
            <hr />
            <p>&copy; @DateTime.Now.Year - Romuald Leroux</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

M2Link/M2Link/Views/Shared/GuestLayout.cshtml
@using M2Link.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
</head>

<body>
    <div class="d-flex h-100 mx-auto flex-column">
        <main role="main" class="w-75 m-auto">
            @RenderBody()
        </main>

        <footer class="mt-auto mx-auto text-center w-75">
            <hr />
            <p>&copy; @DateTime.Now.Year - Romuald Leroux</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

M2Link/M2Link/Views/Shared/NotFound.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Erreur</title>
</head>
<body>

    <div class="text-center">
        <h1 class="mb-5" style="font-size: 150px"><strong>404</strong></h1>
        @Html.ActionLink("Retour à la page d'accueil", "Index", "Home", null, new { @class= "btn btn-secondary" })
    </div>
</body>
</html>

M2Link/M2Link/Views/Shared/_Message.cshtml
@model MessageModel

<div class="message row mb-2">
    <div class="col-12">
        <div class="container-fluid p-0 card">
            <div class="card-body px-3">
                <div class="row">
                    <div class="col">
                        <div class="row mb-2">
                            <div class="col">
                                <a href="@Url.Action("GetProfile", "User", new { u = Model.Author.Username })">
                                    <img class="mr-1 avatar" src="~/Content/Images/Users/@Model.Author.Avatar" width="30" height="30" />
                                </a>
                                @Html.RouteLink((string)@Model.Author.Username, "GetProfile", new { u = @Model.Author.Username })
                                <small class="text-muted" style="color:gray!important">(@Model.Author.FirstName @Model.Author.LastName, le @Model.Date.ToString("dd MMMM yyyy à hh:mm:ss"))</small>

                                @if (User.Identity.Name == Model.Author.Id.ToString())
                                {
                                    <button id="@Model.Id" class="btn btn-delete btn-outline-danger p-0" style="float:right;">
                                        <i class="material-icons align-middle" style="font-size:26px">close</i>
                                    </button>
                                }

                            </div>
                        </div>
                        <div class="row">
                            @if (!string.IsNullOrEmpty(@Model.Image))
                            {
                                <div class="col-12 col-md-4 m-auto message-image">
                                    <a href="~/Content/Images/Messages/@Model.Image" target="_blank"><img src="~/Content/Images/Messages/@Model.Image" class="img-fluid rounded mx-auto d-block" /></a>
                                </div>
                                <div class="col-12 col-md-8">
                                    <blockquote class="text-muted text-justify my-2">@Model.Content</blockquote>
                                </div>
                            }
                            else
                            {
                                <div class="col">
                                    <blockquote class="text-muted text-justify my-2">@Model.Content</blockquote>
                                </div>
                            }
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>