M2Link/M2Link/Controllers/LoginController.cs
using M2Link.Entities;
using M2Link.Models;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace M2Link.Controllers
{
    public class LoginController : Controller
    {
        // GET : Login/Form
        public ActionResult Form()
        {
            // If the user is already authenticated, redirection on Home page
            if (User.Identity.IsAuthenticated)
            {
                return Redirect("/");
            }

            return View(new LoginModel());
        }

        // POST : Login/Form
        [HttpPost]
        public ActionResult Form(LoginModel model)
        {
            // If the model is not valid, redirect on the same page with model errors
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            User user = UserRepository.Instance.FindByUsername(model.Username);

            // If no user with specified credentials were found
            if (user == null)
            {
                ModelState.AddModelError("Username", "L'utilisateur n'existe pas");
                return View(model);
            }

            // If the hashed password does not match with the hash of the specified password
            if (user.Password != Crypto.SHA256(model.Password))
            {
                ModelState.AddModelError("Password", "Le mot de passe est incorrect");
                return View(model);
            }

            // If credentials are correct, setting up a authentication cookie
            FormsAuthentication.SetAuthCookie(user.Id.ToString(), true);
            
            // Redirect on the Home page
            return Redirect("/");
        }

        // GET: Login/Logout
        public void Logout()
        {
            // Logout from the application and redirect to the login page
            FormsAuthentication.SignOut();
            FormsAuthentication.RedirectToLoginPage();
        }
    }
}

M2Link/M2Link/Controllers/RegisterController.cs
using M2Link.Entities;
using M2Link.Models;
using System;
using System.Web.Helpers;
using System.Web.Mvc;

namespace M2Link.Controllers
{
    public class RegisterController : Controller
    {
        // GET : Register/Form
        public ActionResult Form()
        {
            // If the user is already authenticated, redirection on Home page
            if (User.Identity.IsAuthenticated)
            {
                return Redirect("/");
            }

            return View(new RegisterModel());
        }

        // POST : Register/Form
        [HttpPost]
        public ActionResult Form(RegisterModel model)
        {
            // If the model is not valid, redirect on the same page with errors
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                // Create the new user from model data
                UserRepository.Instance.Add(new User
                {
                    FirstName = model.FirstName.Trim(),
                    LastName = model.LastName.Trim(),
                    Mail = model.Mail.Trim(),
                    Username = model.Username.Trim(),
                    Password = Crypto.SHA256(model.Password)
                });
            }
            // If an error occured during the creation of the user account
            catch (ApplicationException e)
            {
                // Show the approriate error
                if (e.Message == UserRepository.MAIL_ALREADY_EXIST_MESSAGE)
                {
                    ModelState.AddModelError("Mail", e.Message);
                }
                else if (e.Message == UserRepository.USERNAME_ALREADY_EXIST_MESSAGE)
                {
                    ModelState.AddModelError("Username", e.Message);
                }

                // Redirect on the same page with model errors
                return View(model);
            }

            // Redirect on the Home page
            return Redirect("/");
        }
    }
}

M2Link/M2Link/Views/Login/Form.cshtml
@model LoginModel
@using M2Link.Helpers

@{
    ViewBag.Title = "Connexion";
}

<div class="container-fluid mt-3">
    <div class="row justify-content-center">
        <div class="col-12 col-md-4 p-0 text-custom">
            <div class="container-fluid p-0 card section" >
                <div class="card-header text-center">
                    <h3 class="mb-0">Connexion</h3>
                </div>

                <div class="card-body px-3">
                    @{Html.BeginForm(null, null, FormMethod.Post);}

                    <div class="form-row">
                        <div class="form-group col">
                            @Html.LabelFor(m => m.Username, new { @class = "sr-only" })
                            @Html.IconTextBoxFor(m => m.Username, "person", new { @class = "form-control", placeholder = "Votre pseudo", maxlength = 30})
                            <small class="form-text">@Html.ValidationMessageFor(m => m.Username)</small>
                        </div>
                    </div>

                    <div class="form-row mb-2">
                        <div class="form-group col">
                            @Html.LabelFor(m => m.Password, new { @class = "sr-only" })
                            @Html.IconTextBoxFor(m => m.Password, "vpn_key", new { @class = "form-control", placeholder = "Votre mot de passe", type = "password", maxlength = 30})
                            <small class="form-text">@Html.ValidationMessageFor(m => m.Password)</small>
                        </div>
                    </div>

                    <div class="form-row justify-content-center mb-3">
                        <input class="col-12 col-md-5 py-2 btn btn-secondary" type="submit" value="Se connecter" />
                    </div>

                    <div class="row justify-content-center text-center">
                        <div class="col-12">
                            <a href="#">Mot de passe oublié ?</a>
                        </div>
                    </div>
                    @{Html.EndForm();}
                </div>
            </div>

            <div class="container-fluid p-0 card mt-4 section">
                <div class="card-body px-3">
                    <div class="row justify-content-center text-center">
                        <span class="col">Vous n'avez pas de compte ? @Html.ActionLink("Inscrivez-vous", "Form", "Register")</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>